In [1]:
import pandas as pd
df = pd.read_csv(r'data\employees.csv')
df.head()

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0

In [2]:
print(df.salary.mean())
# 数据的导出
df = df.tail()
df.to_csv(r"data\new.csv")

6461.682242990654

In [3]:
# json
df = pd.read_json('data/test.json')
print(df.head())
import json
with open('data/test.json',encoding='utf=8') as f:
    data = json.load(f)
print(data)
print(type(data))
df = pd.DataFrame(data['users'])
df

                                               users
0  {'id': 1, 'name': '张三', 'age': 28, 'email': 'z...
1  {'id': 2, 'name': '李四', 'age': 35, 'email': 'l...
2  {'id': 3, 'name': '王五', 'age': 24, 'email': 'w...
{'users': [{'id': 1, 'name': '张三', 'age': 28, 'email': 'zhangsan@example.com', 'is_active': True, 'join_date': '2022-03-15'}, {'id': 2, 'name': '李四', 'age': 35, 'email': 'lisi@example.com', 'is_active': False, 'join_date': '2021-11-02'}, {'id': 3, 'name': '王五', 'age': 24, 'email': 'wangwu@example.com', 'is_active': True, 'join_date': '2023-01-20'}]}
<class 'dict'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [4]:
# 缺失值的处理NAN
import  pandas as pd
import  numpy as np
s = pd.Series([12,23,np.nan,None,pd.NA])
df = pd.DataFrame([[1,pd.NA,2], [2,3,5], [None,5,6]],
                  columns=['第一列', '第二列', '第三列'],
                  index=['第一行', '第二行', '第三行'])
print(s)
print(df)
print("-"*30)
# 缺失值的检测
print(s.isna())
print("-"*30)
print(s.isnull())
print("-"*30)
print(df.isna())
print(df.isnull())

0      12
1      23
2     NaN
3    None
4    <NA>
dtype: object
     第一列   第二列  第三列
第一行  1.0  <NA>    2
第二行  2.0     3    5
第三行  NaN     5    6
------------------------------
0    False
1    False
2     True
3     True
4     True
dtype: bool
------------------------------
0    False
1    False
2     True
3     True
4     True
dtype: bool
------------------------------
       第一列    第二列    第三列
第一行  False   True  False
第二行  False  False  False
第三行   True  False  False
       第一列    第二列    第三列
第一行  False   True  False
第二行  False  False  False
第三行   True  False  False

In [5]:
print(s.isna().sum())
print('-'*30)
print(df.isna().sum())  # 列
print(df.isna().sum(axis=1))  # 行

3
------------------------------
第一列    1
第二列    1
第三列    0
dtype: int64
第一行    1
第二行    0
第三行    1
dtype: int64

In [6]:
# 剔除缺失值
print(s.dropna())
print("-"*30)
print(df)
print(df.dropna())  # 删掉全部有缺失值的行
print(df.dropna(how='all'))     # 所有的值都是缺失值才删除
print(df.dropna(thresh=2))     # 至少有n个值不是缺失值，才保留
print("-"*30)
print(df.dropna(axis=1))    # 删除有缺失值的列

0    12
1    23
dtype: object
------------------------------
     第一列   第二列  第三列
第一行  1.0  <NA>    2
第二行  2.0     3    5
第三行  NaN     5    6
     第一列 第二列  第三列
第二行  2.0   3    5
     第一列   第二列  第三列
第一行  1.0  <NA>    2
第二行  2.0     3    5
第三行  NaN     5    6
     第一列   第二列  第三列
第一行  1.0  <NA>    2
第二行  2.0     3    5
第三行  NaN     5    6
------------------------------
     第三列
第一行    2
第二行    5
第三行    6

In [7]:
# 填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN       NaN       NaN   NaN     NaN
1457  2015-12-28            NaN       NaN       NaN   NaN     NaN
1458  2015-12-29            NaN       NaN       NaN   NaN     NaN
1459  2015-12-30            NaN       NaN       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [8]:
df.isna().sum()
df.head()
print(df.fillna({'temp_max':20,
                 'wind':2.5}).tail())    # 使用字典来填充
print(df.fillna(df[['wind']].mean()).tail())    # 使用统计值来填充
print(df.ffill().tail())    # front使用前面的值填充
print(df.bfill().tail())    # behind使用后面的值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind weather
1456  2015-12-27            NaN       NaN       NaN  3.242055     NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055     NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055     NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055     NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [9]:
# 重复值处理
import pandas as pd
data = {
    "name": ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    "age": [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}

df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [10]:
# 检查重复值
print(df.duplicated()) # 一整条都是相同的，标记为重复，返回True
print(df.drop_duplicates(subset=['name'])) # 根据指定的列去重（留下了旧的信息）
print(df.drop_duplicates(subset=['name'], keep='last')) # 保留最新的数据

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF
    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [11]:
# 数据类型的转换
df = pd.read_csv('data/sleep.csv')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [12]:
df['age'] = df['age'].astype('int16')
df.dtypes

person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [13]:
print(df.gender.tail())
# gender中只有两种元素，可以更换格式
df['gender'] = df['gender'].astype('category')
# 变成了列表
df.gender

395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, dtype: str

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [14]:
df['is_male'] = df['gender'].map({'Female':False, 'Male':True})
df.is_male

0       True
1      False
2       True
3       True
4       True
       ...
395    False
396    False
397    False
398    False
399     True
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [False, True]

In [15]:
# 数据变形
import pandas as pd

data = {
    'ID': [1, 2],
    'name': ['alice', 'bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df.T
df

   ID   name  Math  English  Science
0   1  alice    90       88       95
1   2    bob    85       92       89

In [16]:
# 宽表转换成长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')

   ID   name       科目  分数
0   1  alice     Math  90
2   1  alice  English  88
4   1  alice  Science  95
1   2    bob     Math  85
3   2    bob  English  92
5   2    bob  Science  89

pd.melt() 的执行过程就像 “拆积木”，步骤如下：
- 保留标识列：先把 id_vars 里的 ID、name 列完整保留，作为每一行的基础标识；
- 拆分非标识列：把剩下的 Math、English、Science 列拆成两部分：
- 列名（Math/English/Science）→ 作为 “科目” 列的取值；
- 列值（90/85/88 等）→ 作为 “分数” 列的取值；
- 重组行：每一个 “标识列组合 + 一个科目 + 一个分数” 形成一行，最终生成长表。

In [17]:
# 长表转宽表
pd.pivot(df2,index=['ID','name'],columns='科目', values='分数').reset_index()

科目  ID   name  English  Math  Science
0    1  alice       88    90       95
1    2    bob       92    85       89

In [18]:
import pandas as pd
data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob smith'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df

   ID         name  Math  English  Science
0   1  alice smith    90       88       95
1   2    bob smith    85       92       89

In [19]:
# 分列
df[['first', 'last']] = df['name'].str.split(' ',expand=True)

In [20]:
df = pd.read_csv('data/sleep.csv')
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia

In [21]:
df = df[['person_id', 'blood_pressure']]
print(df.head())
df[['high', 'low']] = df['blood_pressure'].str.split('/',expand=True)
df[['high','low']] = df[['high','low']].astype('int64')
df.info()

   person_id blood_pressure
0          1         124/70
1          2         131/86
2          3         122/70
3          4         124/72
4          5         133/78
<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    str
 2   high            400 non-null    int64
 3   low             400 non-null    int64
dtypes: int64(3), str(1)
memory usage: 12.6 KB

In [22]:
# 数据分箱  pd.cut(x,bins,labels)
import pandas as pd
df = pd.read_csv('data/employees.csv')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [23]:
df1 = df.head(10)[['employee_id', 'salary']]
pd.cut(df1['salary'],bins=2)
# bins为整数：分成n段区间，起始值、结束值是所有数据的最小值、最大值
pd.cut(df1['salary'],bins=3).value_counts() # 统计各个区间的人数

salary
(4180.2, 10800.0]     6
(10800.0, 17400.0]    3
(17400.0, 24000.0]    1
Name: count, dtype: int64

In [24]:
# bins = list列表
pd.cut(df1['salary'],bins=[0,10000,20000,30000]).value_counts()
df1['收入范围'] = pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中', '高'])
print(df1)

# 等分：每段人数相等
pd.qcut(df1['salary'],3).value_counts()

   employee_id   salary 收入范围
0          100  24000.0    高
1          101  17000.0    中
2          102  17000.0    中
3          103   9000.0    低
4          104   6000.0    低
5          105   4800.0    低
6          106   4800.0    低
7          107   4200.0    低
8          108  12000.0    中
9          109   9000.0    低

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [25]:
# 睡眠数据
df = pd.read_csv('data/sleep.csv')
df1 = df.head(10)[['person_id', 'sleep_quality']]
df['睡眠质量'] = pd.cut(df['sleep_quality'],bins=3,
                         labels=['差','中', '优秀'])
df['睡眠质量'].value_counts()
df.head(10)
df['gender'] = df['gender'].astype('category')
df['gender'].value_counts()
# 字符串-->类别-->统计
# 数值-->分箱-->统计
print(df['gender'].dtype)
print(df['睡眠质量'].dtype)

category
category